name: clang-format Check

on: [ pull_request ]

jobs:
  warning-check:
    name: Warning Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check warnings
        run: |
          g++ -std=c++2a -Wall -Wextra -Wconversion -Wsign-conversion -pedantic \
            -I include/ -Werror src/*.cpp example/main.cpp

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: '13'
          check-path: '.'
#          fallback-style: 'Mozilla' # optional
